### ISSUE TITLE
sea.test.fixtures 中的 app 和 db fixture 的 scope 应该为 `session`

### ISSUE THREAD

**Issue by earlzo** [shanbay/sea#90]
默认的 fixture scope 为 function, 将其作为 test function 的参数每次都会生成一遍.

app, db 这两个 fixture 的数据应当是全局的, 尤其是 db , 每次以它为参数都会进行一次 migrate , 这是相当耗时的, 并且也没有这个必要.

相应文档见:
[Scope: sharing a fixture instance across tests in a class, module or session](https://docs.pytest.org/en/latest/fixture.html#scope-sharing-a-fixture-instance-across-tests-in-a-class-module-or-session)

**Comment by yandy** [comment]
这个就是要 function 的 scope，每个function都是独立的
